# Dockerfile for the client
FROM node:current-alpine3.17 AS build

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm ci

COPY . .


FROM alpine:3.16

WORKDIR /usr/src/app

RUN apk update && apk add npm

COPY --from=build /usr/src/app .

EXPOSE 3000

CMD ["npm", "start"]