# Dockerfile for the backend

FROM node:current-alpine3.17 AS build

WORKDIR /usr/src/app

COPY ./package*.json ./
RUN npm ci
COPY . .


FROM alpine:3.16

WORKDIR /usr/src/app

RUN apk update && apk add --update nodejs
COPY --from=build /usr/src/app .
EXPOSE 5000

CMD ["node", "server.js"]
